apiVersion: v1
kind: Namespace
metadata:
  name: demo
  namespace: demo
  labels:
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: default

---

apiVersion: v1
kind: Namespace
metadata:
  name: kong
  namespace: kong
  labels:
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: default
