env:
  trusted_ips: 0.0.0.0
  log_level: debug
  plugins: bundled,oidc, opa, phantom-token,myheader2

image:
  tag: 2.5a
  repository: atamos/kong 

plugins:
  configMaps:                
  - name: kong-plugin-phantom-token
    pluginName: phantom-token
  - name: kong-plugin-myheader2
    pluginName: myheader2
  # - name: kong-plugin-opa
  #   pluginName: opa
proxy:
    http:
      enabled: true
      servicePort: 8000
      containerPort: 8000
      parameters: []

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    parameters: []
     

